/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author halae
 */
public class AnimalFarm extends javax.swing.JFrame {

    /**
     * Creates new form AnimalFarm
     */
    public AnimalFarm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Dog = new javax.swing.JButton();
        Toad = new javax.swing.JButton();
        Alligator = new javax.swing.JButton();
        Chicken = new javax.swing.JButton();
        Shark = new javax.swing.JButton();
        Crow = new javax.swing.JButton();
        Cow = new javax.swing.JButton();
        Cat = new javax.swing.JButton();
        Owl = new javax.swing.JButton();
        Dolphin = new javax.swing.JButton();
        Frog = new javax.swing.JButton();
        Crocodile = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Quit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel1.setLayout(new java.awt.GridLayout(4, 3));

        Dog.setText("Dog");
        Dog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Dog);

        Toad.setText("Toad");
        Toad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Toad);

        Alligator.setText("Alligator");
        Alligator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Alligator);

        Chicken.setText("Chicken");
        Chicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Chicken);

        Shark.setText("Shark");
        Shark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Shark);

        Crow.setText("Crow");
        Crow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Crow);

        Cow.setText("Cow");
        Cow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Cow);

        Cat.setText("Cat");
        Cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Cat);

        Owl.setText("Owl");
        Owl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Owl);

        Dolphin.setText("Dolphin");
        Dolphin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Dolphin);

        Frog.setText("Frog");
        Frog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Frog);

        Crocodile.setText("Crocodile");
        Crocodile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Crocodile);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        Quit.setText("Quit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });
        jMenu1.add(Quit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        jMenu2.add(About);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(null, "CNIT25501 Final Project\n\nDevloped by Palwasha Khan (0034238927) and Halaevalu Patterson(0033530652)\n\n\n\n\nPS: The alligator fact is correct.");
    }//GEN-LAST:event_AboutActionPerformed

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_QuitActionPerformed

    private void AnimalButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimalButtonPressed
    Animal animal = null;
    String buttonLabel = evt.getActionCommand();
    switch (buttonLabel) {
        case "Dog":
            animal = new Mammal("Dog", 11, 13, "Meat & Dog Food", "Omnivore", "Dogs can sniff at the same time as breathing.");//, dogSound);
            break;
        case "Cat":
            animal = new Mammal("Cat", 15, 15, "Cat food & Meat", "Carnivore", "A house cat is genetically 95.6% tiger.");//, catSound);
            break;
        case "Cow":
            animal = new Mammal("Cow", 4, 20, "Pasture Grasses & Hay", "Herbivore", "Even though cows only sleep 4 hours, they drowse for 8 hours.");//, catSound);
            break;
        case "Shark":
            animal = new Fish("Shark", 0, 25, "Fish & Invertebrates", "Carnivore", "Instead of sleeping (like we think), sharks take a period of rest by gliding down instead of swimming.");//, catSound);
            break;
        case "Dolphin":
            animal = new Fish("Dolphin", 8, 15, "Fish, Squid, Crustaceans", "Carnivore", "Dolphins sleep with only 1/2 of their brain at a time.");//, catSound);
            break;
        case "Owl":
            animal = new Bird("Owl", 12, 10, "Mice, Squirrels, & Small Animals", "Carnivore", "Owls can turn their head 270 degrees (almost a full circle!)");//, catSound);
            break;   
        case "Chicken":
            animal = new Bird("Chicken", 8, 7, "Weeds, Seeds, & Insects", "Omnivore", "Chickens are descendants of dinosaurs (maybe they should be roaring instead of bawking).");//, catSound);
            break;
        case "Crow":
            animal = new Bird("Crow", 10, 8, "Insects, Small Animals, Fruit, & Seeds", "Omnivore", "There's a book called Six of Crows... It's not about crows. You should read it anyway.");//, catSound);
            break;
        case "Frog":
            animal = new Amphibian("Frog", 13, 20, "Insects & Invertebrates", "Carnivore", "Tell frogs and toads apart: Frogs have longer legs (longer than their head and body) meant for hopping. Frogs have smooth and slimy skin.");//, catSound);
            break;
        case "Toad":
            animal = new Amphibian("Toad", 14, 12, "Insects & Anthropods", "Carnivore", "Tell frogs and toads apart: Toads have shorter legs than frogs and prefer to crawl around rather than hop. Toads have dry, warty skin.");//, catSound);
            break;
        case "Alligator":
            animal = new Reptile("Alligator", 17, 40, "Fish, Invertebrates, & Small Mammals", "Carnivore", "Tell alligators and crocodiles apart: Crocodiles are more aggressive, while alligators only attack when hungry or provoked.");//, catSound);
            break;
        case "Crocodile":
            animal = new Reptile("Crocodile", 17, 65, "Insects, Fish, & Small Frogs", "Carnivore", "Tell alligators and crocodiles apart: Alligators are more aggressive, while crocodiles only attack when hungry or provoked.");//, catSound);
            break;
    }
    if (animal != null) {
        displayAnimalInfo(animal);
    }
}

    public void displayAnimalInfo(Animal animal) {
        // display the animal information in the GUI
        String animalInfo = animal.getInfo();
        javax.swing.JOptionPane.showMessageDialog(null, animalInfo);
        
    }//GEN-LAST:event_AnimalButtonPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalFarm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JButton Alligator;
    private javax.swing.JButton Cat;
    private javax.swing.JButton Chicken;
    private javax.swing.JButton Cow;
    private javax.swing.JButton Crocodile;
    private javax.swing.JButton Crow;
    private javax.swing.JButton Dog;
    private javax.swing.JButton Dolphin;
    private javax.swing.JButton Frog;
    private javax.swing.JButton Owl;
    private javax.swing.JMenuItem Quit;
    private javax.swing.JButton Shark;
    private javax.swing.JButton Toad;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
