/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author halae
 */
public class AnimalFarm extends javax.swing.JFrame {

    /**
     * Creates new form AnimalFarm
     */
    public AnimalFarm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Dog = new javax.swing.JButton();
        Toad = new javax.swing.JButton();
        Alligator = new javax.swing.JButton();
        Chicken = new javax.swing.JButton();
        Shark = new javax.swing.JButton();
        Crow = new javax.swing.JButton();
        Cow = new javax.swing.JButton();
        Cat = new javax.swing.JButton();
        Owl = new javax.swing.JButton();
        Dolphin = new javax.swing.JButton();
        Frog = new javax.swing.JButton();
        Crocodile = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Quit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel1.setLayout(new java.awt.GridLayout(4, 3));

        Dog.setText("Dog");
        Dog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Dog);

        Toad.setText("Toad");
        Toad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Toad);

        Alligator.setText("Alligator");
        Alligator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Alligator);

        Chicken.setText("Chicken");
        Chicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Chicken);

        Shark.setText("Shark");
        Shark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Shark);

        Crow.setText("Crow");
        Crow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Crow);

        Cow.setText("Cow");
        Cow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Cow);

        Cat.setText("Cat");
        Cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Cat);

        Owl.setText("Owl");
        Owl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Owl);

        Dolphin.setText("Dolphin");
        Dolphin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Dolphin);

        Frog.setText("Frog");
        Frog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Frog);

        Crocodile.setText("Crocodile");
        Crocodile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButtonPressed(evt);
            }
        });
        jPanel1.add(Crocodile);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        Quit.setText("Quit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });
        jMenu1.add(Quit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        jMenu2.add(About);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(null, "CNIT25501 Final Project\n\nDevloped by Palwasha Khan and Halaevalu Patterson");
    }//GEN-LAST:event_AboutActionPerformed

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_QuitActionPerformed

    private void AnimalButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimalButtonPressed
        // TODO add your handling code here:
        if (evt.getSource() instanceof JButton) {
            JButton button = (JButton) evt.getSource();
            String buttonName = button.getName();
            if (buttonName.equals("button1")) {
                // Code to be executed when button1 is clicked
            }
        }
        //if ()
        //Animal animal = new Animal();
    }//GEN-LAST:event_AnimalButtonPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalFarm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JButton Alligator;
    private javax.swing.JButton Cat;
    private javax.swing.JButton Chicken;
    private javax.swing.JButton Cow;
    private javax.swing.JButton Crocodile;
    private javax.swing.JButton Crow;
    private javax.swing.JButton Dog;
    private javax.swing.JButton Dolphin;
    private javax.swing.JButton Frog;
    private javax.swing.JButton Owl;
    private javax.swing.JMenuItem Quit;
    private javax.swing.JButton Shark;
    private javax.swing.JButton Toad;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
